name: tagit_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter

  # 상태관리
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # UI
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  shadcn_ui: ^0.22.5

  # Utility
  go_router: ^14.8.0
  dio: ^5.8.0+1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  mockito: ^5.4.5
  permission_handler: ^11.4.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

  build_runner:
  riverpod_generator:
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true

